# String Format

String中的format方法： 代替字符串中的格式化参数

In [38]:
template = '{0:.2f} {1:s} are worth US${2:d}'
# {0:.2f}：表示第一个参数保留到小数点后两位小数
# {1:s}：表示第二个参数为字符串
# {2:d}：第三个参数为整数
template.format(4.5560, 'Argentine Pesos', 1)


'4.56 Argentine Pesos are worth US$1'

# Data files and summary statistics

In [39]:
import csv
# precision with 2
with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
mpg[:3]

FileNotFoundError: [Errno 2] No such file or directory: 'mpg.csv'

# Dates and Times

## Looking for the time right now

In [ ]:
import datetime as dt
import time as tm
tm.time()

In [ ]:
datetime_now = dt.datetime.fromtimestamp(tm.time())
datetime_now

In [ ]:
datetime_now.year, datetime_now.month

## What is a hundred day before today

In [ ]:
delta = dt.timedelta(days = 100)
delta

In [ ]:
today = dt.date.today()

In [ ]:
today-delta

# Numpy

# Array Creation

In [46]:
import numpy as np
import math
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)

2


In [47]:
# length of dimention
a.shape

(2, 3)

In [48]:
# type of items
a.dtype 

dtype('int32')

In [50]:
# zero array
d = np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [51]:
# random array
np.random.rand(2,3)

array([[0.12439581, 0.34158007, 0.93087649],
       [0.60860443, 0.76251969, 0.24202512]])

In [54]:
# generate array with increment 2
f = np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [56]:
# linspace command
np.linspace(0, 2, 15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

## Array Operations

In [58]:
# * is the element wise multiplication opertator
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print(a*b)

[ 10  40  90 160]


In [60]:
# @ is the matrix product opertator
a = np.array([[2,3],
              [4,5]])
b = np.array([[3,4],
             [2,4]])
print(a@b)

[[12 20]
 [22 36]]


In [64]:
# reshape array into matrix
a = np.arange(1,26,1).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])